cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove')
]

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOISES = [(i, str(i)) for i in range(1, 11)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOISES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from main.models import Products
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Products, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Products, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Корзина{% endblock title %}

{% block content %}
    <section class ='cart d-flex'>
        <div class="cart-title">
            <h2>Корзина с товарами</h2>
        </div>
        <div class="cart-cards">
            {% for item in cart  %}
                {% with product=item.product %}
                    <div class="cart-card d-flex">
                        <div class="cart-card-img">
                            <img src="{% if product.image %}{{product.image.url}}{% else %}{% static 'img/noimage.png' %}{% endif %}" class="cart_image" alt="">
                        </div>
                        <div class="cart-card-info">
                            <div class="cart-card-name">
                                <p>{{product.name}}</p>
                            </div>
                            <div class="cart-card-q">
                                <p>Количество:{{item.quantity}}</p>
                            </div>
                        </div>
                        <form action="{% url "cart:cart_remove" product.id %}" method = "post">
                            <input type="submit" value="Убрать" class ="remove_button">
                            {% csrf_token %}
                        </form>
                        <div class="cart-card-price">
                            {% if product.discount %}
                                <div class="card-discount d-flex gap-2">
                                    <p class="line">{{product.price}}</p>
                                    <p>{{product.sell_price}}</p>
                                </div>
                            {% else %}
                                <p class="price">{{product.price}}</p>
                            {% endif %}
                        </div>
                    </div>
                {% endwith %}
            {% endfor %}
        </div>
        <div class="total">
            <h5>Общая сумма: {{cart.get_total_price}}</h5>
        </div>
        <div class="cart-buttons d-flex gap-3">
            <a href="/shop" class="cart-button">Продолжить покупки</a>
            {% with cart_quantity=cart|length %}
                {% if cart_quantity > 0 %}
                    <a href="{% url 'orders:order_create' %}" class="cart-button">Оплатить</a>
                {% endif %}
            {% endwith %}
        </div>
    </section>


{% endblock content %}