main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.popular_list, name='popular_list'),
    path('shop/', views.product_list, name = 'product_list'),
    path('shop/<slug:slug>/', views.product_detail, name='product_detail'),
    path('shop/category/<slug:category_slug>/', views.product_list, name = 'product_list_by_category'),
]

main/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    
    class Meta:
        ordering=['name']
        indexes = [models.Index(fields=['name'])]
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def get_absolute_url(self):
        return reverse("main:product_list_by_category",
                       args=[self.slug])
    
    
    def __str__(self):
        return self.name
    
class Products(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    image = models.ImageField(upload_to='products/%Y%m/%d')
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    discount = models.DecimalField(default=0.00, max_digits=4, decimal_places=2)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['created']),
            ]


    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('main:product_detail',
                       args = [self.slug])
    
    def sell_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount / 100, 2)
        return self.price
    

main/views.py
from django.shortcuts import render, get_object_or_404
from .models import Products, Category
from django.core.paginator import Paginator
from cart.forms import CartAddProductForm

def popular_list(request):
    products = Products.objects.filter(available=True)[:5]
    return render(request, 'main/index/index.html',
                  {"products":products})


def product_detail(request, slug):
    product = get_object_or_404(Products,
                                slug = slug,
                                available=True)
    cart_product_form = CartAddProductForm
    
    return render(request,
                  'main/product/detail.html',
                  {'product':product,
                   'cart_product_form': cart_product_form})


def product_list(request, category_slug = None):
    page = request.GET.get('page', 1)
    category = None
    categories = Category.objects.all()
    products = Products.objects.filter(available=True)
    paginator = Paginator(products, 10)
    current_page = paginator.page(int(page))
    if category_slug:
        category = get_object_or_404(Category, slug = category_slug)
        paginator = Paginator(products.filter(category=category), 10)
        current_page = paginator.page(int(page))
    return render(request, 
                  'main/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': current_page,
                   'slug_url': category_slug})

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>

    {% comment %} bootstrap {% endcomment %}
    <link rel="stylesheet" href="{% static 'bootstrap\css\bootstrap.min.css' %}">

    {% comment %} css {% endcomment %}
    <link rel="stylesheet" href="{% static 'css\base.css' %}">
</head>
<body>
    <header class="header sticky-top">
        <div class="header-container d-flex">
            <navbar class="header-nav pt-4">
                <ul class="header-list d-flex">
                    <li>
                        <a href="/" class = "nav-a m-3">ГЛАВНОЕ МЕНЮ</a>
                    </li>
                    <li>
                        <a href="/shop" class = "nav-a m-3">МАГАЗИН</a>
                    </li>
                </ul>
            </navbar>
            <div class="header-logo">
                <a href="/shop"><img src="{% static 'img/logo.webp' %}" alt="" class="shop-logo"></a>
            </div>
            <div class="header-profile pt-2">
                <a href="{% url 'cart:cart_detail' %}">
                    <img src={% static 'img/cart.png' %} class="cart-img" alt="">
                </a>
                <a href="{% url "users:login" %}" class="m-2">АВТОРИЗОВАТЬСЯ</a>
                <p class="cart-quantity">
                    {% with cart_quantity=cart|length %}
                        {% if cart_quantity > 0 %}
                            {{cart_quantity}}
                        {% else %}
                            0
                        {% endif %}
                    {% endwith %}
                </p>
            </div>
        </div>
    </header>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
    {% comment %} JS for bootstrap {% endcomment %}
    <script src="{% static 'bootstrap\js\bootstrap.bundle.min.js' %}"></script>
</body>
</html>

main/templates/main/index/index.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Главная{% endblock title %}

{% block content %}
    <section class="home d-flex flex-column">
        <div class="home-tutle d-flex flex-column align-items-center">
            <a href="#" class="home_button mt-4">ВСЕ ТОВАРЫ</a>
        </div>
        <div class="home-recomendation">
            <div class="rec-title mb-4">
                <h3><span>Популярные товары</span></h3>
            </div>
        </div>
        <div class="home-cards d-flex gap-4">
            {% for product in products %}
            <a href="{{product.get_absolute_url}}" class="home-card d-flex flex-column align-items-center text-center">
                <img src="{% if product.image %}{{product.image.url}}{% else %}{% static 'img/noimage.png' %}{% endif %}" class="card-img" alt="">
                <h5 class="title-card">{{product.name}}</h5>
                {% if product.discount %}
                <div class="card-discount d-flex gap-2">
                    <p class="line">{{product.price}}</p>
                    <p class="sell-price">{{product.sell_price}}</p>
                </div>
                {% else %}
                    <p class="price">{{product.price}}</p>
                {% endif %}
            </a>
            {% endfor %}

        </div>
    </section>
    
    <img src="{% static 'img/logo.png' %}" class="logotype" alt="">
    <img src="{% static 'img/subtitle.png' %}" class="subtitlee" alt="">
{% endblock content %}

main/templates/main/product/detail.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}
    {{product.name}}
{% endblock title %}

{% block content %}
    <div class="detail-product d-flex">
        <div class="detail-img">
            <img src="{% if product.image %}{{product.image.url}}{% else %}{% static 'img/noimage.png' %}{% endif %}" class="detail-image"alt="">
        </div>
        <div class="detail-description">
            <h2>{{product.name}}</h2>
            <h3>Категория: {{product.category}}</h3>
            <p>Описание: {{product.description|linebreaks}}</p>
            {% if product.discount %}
                <div class="card-discount d-flex gap-2">
                    <p class="line">{{product.price}}</p>
                    <p class="sell-price">{{product.sell_price}}</p>
                </div>
            {% else %}
                <p class="price">{{product.price}}</p>
            {% endif %}
            <form action="{% url "cart:cart_add" product.id %}" class="qform" method="post">
                <div class="cart-form">
                    {{cart_product_form}}
                    {% csrf_token %}
                </div>
                <input type="submit" class="add-to-cart-button" value ="Добавить">
            </form>
        </div>
    </div>
{% endblock content %}

main/templates/main/product/list.html
{% extends "main/base.html" %}
{% load static %}
{% block title  %}Магазин{% endblock title  %}

{% block content %}
<div class="list d-flex">
    <div class="sidebar">
        <h3>Категории</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url "main:product_list" %}">ВСЕ</a>
            </li>
            {% for c in  categories %}
                <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                    <a href="{{c.get_absolute_url}}">{{c.name}}</a>
                </li>
            {% endfor %}
        </ul>
    </div>    
    <div class="main">
        <div class="main-title">
            {% if category %}{{category.name}}{% else %}ТОВАРЫ{% endif %}
        </div>
        <div class="product-list">
            <div class="items">
                {% for product in products %}
                    <div class="item">
                        <a href="{{product.get_absolute_url}}" class ="home-card d-flex flex-column align-items-center text-center">
                            <img src="{% if product.image %}{{product.image.url}}{% else %}{% static 'img/noimage.png' %}{% endif %}" class='card-img' alt="">
                            <h5 class='title-card'>{{product.name}}</h5>
                            {% if product.discount %}
                                <div class="card-discount d-flex gap-2">
                                    <p class="line">{{product.price}}</p>
                                    <p>{{product.sell_price}}</p>
                                </div>
                            {% else %}
                                <p class="price">{{product.price}}</p>
                            {% endif %}
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
        <ul class="pagination">
            <li class="{% if not products.has_previous %}disabled{% endif %}">
                <a href="{% if products.has_previous %}?page={{ products.previous_page_number }}{% endif %}">Назад</a>
            </li>
            {% for page in products.paginator.page_range %}
                {% if page >= products.number|add:-2 and page <= products.number|add:2 %}
                    <li>
                        <a href="?page={{ page }}" class="{% if products.number == page %}disabled{% endif %}">{{ page }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            <li class="{% if not products.has_next %}disabled{% endif %}">
                <a href="{% if products.has_next %}?page={{ products.next_page_number }}{% endif %}">Вперед</a>
            </li>
        </ul>
    </div>
</div>
{% endblock content %}