orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

orders/models.py
from django.db import models
from main.models import Products
from users.models import User

class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete = models.SET_DEFAULT, blank=True, null=True, default=None)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    city = models.CharField(max_length=100)
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default = False)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return f'Order {self.id}'
    
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())
    
class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Products, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)


    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['user', 'first_name', 'last_name', 'email', 'address', 'postal_code', 'city']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)
        if self.request.user.is_authenticated:
            self.initial['first_name'] = self.request.user.first_name
            self.initial['last_name'] = self.request.user.last_name
            self.initial['email'] = self.request.user.email

    def save(self, commit=True):
        order = super().save(commit=False)
        order.user = self.request.user
        if commit:
            order.save()
        return order

orders/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart

def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST, request=request)
        if form.is_valid():
            order = form.save()
            for item in cart:
                discounted_price = item['product'].sell_price()
                OrderItem.objects.create(order=order, product = item['product'], price = discounted_price, quantity = item['quantity'])
            
            cart.clear()
            request.session['order_id'] = order.id
            return redirect(reverse('payment:process'))
        
    else:
        form =  OrderCreateForm(request=request)
    return render(request, 'order/create.html', {'cart': cart, 'form': form})

orders/templates/order/create.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Создание заказа{% endblock title %}

{% block content %}
    <div class="forcreate">
        <div class="profile bg-white p-4 mb-4 mx-2">
            <h2 class="mb-2">Оформление заказа</h2>
            <form action="" method="post" class="order-form">
                {% csrf_token %}
                <div class="col-md-12 mb-3">
                    <label for="id_first_name" class="form-label">Имя</label>
                    <input type="text" class="form-control form-styleprofile" id="id_first_name"
                    name="first_name" placeholder="Ваше Имя" value="{{ form.first_name.value|default:'' }}" required>
                </div>
                <div class="col-md-12 mb-3">
                    <label for="id_last_name" class="form-label">Фамилия</label>
                    <input type="text" class="form-control form-styleprofile" id="id_last_name"
                    name="last_name" placeholder="Ваша Фамилия" value="{{ form.last_name.value|default:'' }}" required>
                </div>
                <div class="col-md-12 mb-3">
                    <label for="id_email" class="form-label">Электронная почта</label>
                    <input type="text" class="form-control form-styleprofile" id="id_email"
                    name="email" placeholder="Ваша Электронная почта" value="{{ form.email.value|default:'' }}" required>
                </div>

                <div class="col-md-12 mb-3">
                    <label for="id_address" class="form-label">Адрес</label>
                    <input type="text" class="form-control form-styleprofile" id="id_address"
                    name="address" placeholder="Ваш Адрес" value="{{ form.address.value|default:'' }}" required>
                </div>
                <div class="col-md-12 mb-3">
                    <label for="id_postal_code" class="form-label">Почтовый индекс</label>
                    <input type="text" class="form-control form-styleprofile" id="id_postal_code"
                    name="postal_code" placeholder="Ваш Почтовый индекс" value="{{ form.postal_code.value|default:'' }}" required>
                </div>
                <div class="col-md-12 mb-3">
                    <label for="id_city" class="form-label">Город</label>
                    <input type="text" class="form-control form-styleprofile" id="id_city"
                    name="city" placeholder="Ваш город" value="{{ form.city.value|default:'' }}" required>
                </div>
                <p><input type="submit" value="Оформить заказ"></p>
                {% csrf_token %}
            </form>
        </div>
        <div class="checkout">
            <h1>Содержимое заказа</h1>
            <div class="order-info">
                {% for item in cart %}
                    <li>
                        {{ item.quantity }}x {{ item.product.name }}
                        <p> {{ item.total_price }}</p>
                    </li>
                    <p>Общая сумма: {{ cart.get_total_price }}</p>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

orders/templates/order/created.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Заказ Создан{% endblock title %}

{% block content %}
    <h1 class='text-center mt-5'>Ваш заказ успешно создан!</h1>
{% endblock content %}